### ISSUE TITLE
API Documentation example isn't working

### ISSUE THREAD

**Issue by bjoernh** [jdemaeyer/brightsky#103]
Hi,
if I try to explore the api with the documentation website https://brightsky.dev/docs/ all api calls failed and returns an error:

_Response Status: Request header field Cache-Control is not allowed by Access-Control-Allow-Headers. (CORS or Network Issue)_

Seems like a misconfiguration with the deployment.

**Comment by jdemaeyer** [comment]
Hi @bjoernh, thanks for the report!

Looks like [rapidoc recently started sending the `Cache-Control` header](https://github.com/mrin9/RapiDoc/pull/294), which we currently don't allow in our CORS settings.

**Comment by jdemaeyer** [comment]
Fixed via 383305e and jdemaeyer/brightsky-infrastructure@e3045e3
