### ISSUE TITLE
Publish the code of the demo page?

### ISSUE THREAD

**Issue by BlackScreen** [jdemaeyer/brightsky#105]
Hey there,
I really like Bright Sky - thanks for your development.
As I want to use pretty much exactly the simple weather app you have on the demo page, I wanted to ask, if you could publish the code of this.
It would be really helpful to me, as I am not that into JavaScript and the demo app is just perfect for my use case.
Thank you for considering my proposal and for the continued development!

**Comment by jdemaeyer** [comment]
Heyho @BlackScreen, thanks for the kind words!

It's already published in this repo under the [`docs/demo` folder](https://github.com/jdemaeyer/brightsky/blob/master/docs/demo/index.html) :) (with the JavaScript starting on line 92)

I'm closing this for now but feel free to re-open if you think something's missing!

**Comment by BlackScreen** [comment]
@jdemaeyer
Thanks for the help, I just did not see that here. Sorry for that.
I copied the whole "demo" folder over to my webspace, but the whole block of the response and the app block do not refresh when i change parameters - unlike on your page. I do not know why. Any idea what I am doing wrong? :/

**Comment by BlackScreen** [comment]
Ok, if I understand correctly this error is solveable with adding a ".htaccess" to your server and adding this to the file:

```
<IfModule mod_headers.c>
	Header set Access-Control-Allow-Origin *
</IfModule>
```

I am obiously no expert on this, but reading [this](https://javascript.info/fetch-crossorigin) and a few other results on Google seem to hint to this. Would adding the header be an option for you or should I look into other solutions?

**Comment by jdemaeyer** [comment]
We are purposefully not setting the CORS headers as it'll interfere with out rate-limiting (although currently we are way below request volumes where our rate limits would apply...)

If you still want to make Bright Sky requests from the frontend (opposed to doing them in the backend and then forwarding the data to your frontend), you can try using this service: https://cors-anywhere.herokuapp.com/

It'll simply forward Bright Sky's response with some additional CORS headers. Just replace

```javascript
const BRIGHTSKY_URL = 'https://api.brightsky.dev/';
```

with

```javascript
const BRIGHTSKY_URL = 'https://cors-anywhere.herokuapp.com/https://api.brightsky.dev/';
```

at the top of the javascript code.

**Comment by BlackScreen** [comment]
I understand. Thank you for your help, it works now! :)

**Comment by jdemaeyer** [comment]
Awesome! :)

**Comment by jdemaeyer** [comment]
Heyho @BlackScreen!

Bright Sky now allows CORS requests from all origins :)
