### ISSUE TITLE
Fix source model in OpenAPI specs

### ISSUE THREAD

**Issue by jdemaeyer** [jdemaeyer/brightsky#114]
Source model misses `first_record` and `last_record` fields

**Comment by tomaculum** [comment]
The `observation_key` enum description states, that there are only four allowed values: 

> Allowed: forecast┃synop┃current┃historical

Yesterday I received a response with a `recent` value in this enum. Unfortunately I can't remember what values and endpoint I used :/

**Comment by jdemaeyer** [comment]
Thanks @tomaculum for the extra info! We have recently dropped the `recent` observation type but the final cleanup [hasn't made it to production yet](https://github.com/jdemaeyer/brightsky/commits/master) (i.e. the docs are slightly ahead of the production deployment). There should be no more `recent` records after the next release.
