### ISSUE TITLE
"relative_humidity" responses are almost null.

### ISSUE THREAD

**Issue by kanpyo02** [jdemaeyer/brightsky#122]
Hi their,

The "relative_humidity" responses are almost null.
We can get the actual relative_humidity, but it seems that there is no relative_humidity with forecast data.
Can we get all relative_humidity?
If we can do it, we can also add "apparent temperature" with temperature, wind speed, and humidity.
Calculator of Apparent temperature
https://planetcalc.com/2089/

Best regards.

**Comment by jdemaeyer** [comment]
Heyho @kanpyo02,

as you correctly observed, while we have real-world-measured `relative_humidity` (i.e. the value is not `null` for most historical and current weather records), it is missing from the forecast data. This is a limitation that we inherit from [MOSMIX](https://www.dwd.de/EN/ourservices/met_application_mosmix/met_application_mosmix.html), the DWD's weather forecast product, which does not include forecasts for relative humidity. The full list of available parameters can be found [here](https://opendata.dwd.de/weather/lib/MetElementDefinition.xml).

So there is unfortunately not much we can do about the missing relative humidity forecasts unless we want to completely uproot our data collection and switch to a different forecast source (interestingly, ICON, which is itself one of the sources for MOSMIX, does have relative humidity predictions).

I'm closing this as "upstream issue", but feel free to re-open if you hard-disagree ;) There is an ongoing discussion about apparent temperature in #112.
