### ISSUE TITLE
`/current_weather` does not accept `source_id`

### ISSUE THREAD

**Issue by jdemaeyer** [jdemaeyer/brightsky#126]
https://api.brightsky.dev/current_weather?source_id=11695 returns code 400.

Either change the endpoint or change the docs

**Comment by hoetzgit** [comment]
Is there any progress yet in correcting this error?

**Comment by jdemaeyer** [comment]
Not yet, but we are entering another funding (read: active development) period the day after tomorrow and I plan to tackle some low-hanging fruit like this issue first, so expect an update within the next two weeks!

**Comment by jdemaeyer** [comment]
Fix will probably land in our public instance later this week. :)

Note that only sources with `observation_type: 'synop'` will yield any data for the `current_weather` endpoint.
