### ISSUE TITLE
No data for United States

### ISSUE THREAD

**Issue by Leo32345** [jdemaeyer/brightsky#127]
This API appears to work in Europe, Asia, but there is no data for anywhere within the United States, resulting in a 404.

**Comment by Leo32345** [comment]
Oops, this is my bad! I forgot to put a negative sign for the longitude.

**Comment by jdemaeyer** [comment]
Glad it worked out! Unfortunately for most locations outside of Germany the DWD only supplies forecasts (as part of MOSMIX), and no current or historical observations.
