### ISSUE TITLE
Solar power

### ISSUE THREAD

**Issue by chrbru** [jdemaeyer/brightsky#141]
Hi, thank's for asking what I am looking for. Maybe my request was already mentioned somewhere and I was blind to find it.
What I like to have on hourly base is a prediction for today and tomorrow about the expected solar radiation. Something like Wh / m². Or I can tell you how my solar panels are aligned in relation to compass direction and inclination, and the api responds with the expected solar power. With this data I like to pre-control my solar based equipment.

**Comment by jdemaeyer** [comment]
One of these days I'll learn to always double my estimates...

I have just released v2.0.1 :tada:. This release makes solar irradiation available as

* `solar` in the `/weather` endpoint (i.e. for measurements and forecasts), and as
* `solar_10` / `solar_30` / `solar_60` in the `/current_weather` endpoint.
 
The database should fill up within the next hour as we (re-)parse the DWD files.

`solar` is the **global irradiation for the past hour**. It will be returned as **kWh / m²** if you're using the default `dwd` units, or J / m² if you're using `si` units.

@chrbru If you can find the time, I would love some feedback if the values look reasonable.

**Comment by jdemaeyer** [comment]
Closing as this is now [officially part of the API](https://brightsky.dev/docs/#/operations/getWeather) :)
