### ISSUE TITLE
API responses very slow since about 3 pm CEST today

### ISSUE THREAD

**Issue by BlackScreen** [jdemaeyer/brightsky#152]
Hey there,
I am using your API and am running into timeouts since about 3 pm today.
Your Grafana dashboards shows this too. Can you have a look at the server, when you have the time?
Thanks for this great API and your work!

**Comment by tawissus** [comment]
True. For me, the last time access worked was around 16:00.

**Comment by BlackScreen** [comment]
Yeah. Access works again now - shortly after midnight there were no timeouts. Thanks for fixing! :)

**Comment by jdemaeyer** [comment]
Hi guys, thanks for the report!

As you said, response times stabilized shortly after midnight. That's when most users changed their queries from `date=2023-08-20` to `date=2023-08-21` -- however, it doesn't seem that there were any changes in the underlying data in the middle of Sunday that would massively impact database query time like this. So I guess it was a hiccup that got reset by some daily maintenance task or rotation.

I'm swamped with work right now so can't investigate deeply, but I'll keep a closer look on the server throughout the day (my monitoring tools actually did pick up the outage yesterday, I just wasn't reachable :see_no_evil:)

**Comment by smilingchemist** [comment]
The problem seems to be back. Last record is from yesterday, 14:30 UTC...

**Comment by BlackScreen** [comment]
> The problem seems to be back. Last record is from yesterday, 14:30 UTC...

Yeah. Was gonna say this too.

**Comment by jdemaeyer** [comment]
Thanks for reporting! New data is currently being parsed and should be available in the next 30 minutes.

This issue originated from a prolonged outage of dwd.de (not the open data server but their official website, from which we load a station list as a prerequisite for parsing) that we should build resilience against. I'll open a new issue in a bit

**Comment by jdemaeyer** [comment]
https://github.com/jdemaeyer/brightsky/issues/154
