### ISSUE TITLE
Current weather data not updating

### ISSUE THREAD

**Issue by smilingchemist** [jdemaeyer/brightsky#153]
Hi,
I'm using your api and there is an issue as the current weather data is not updated since yesterday, 14:30 UTC.
Thank you for your work and this great api!

**Comment by jdemaeyer** [comment]
Thanks for the report, see https://github.com/jdemaeyer/brightsky/issues/152#issuecomment-1703752844 :)

Follow-up: https://github.com/jdemaeyer/brightsky/issues/154
