### ISSUE TITLE
Inconsitency in yml?

### ISSUE THREAD

**Issue by miasbeck** [jdemaeyer/brightsky#156]
For the `/alerts` request, there seems to be a discrepancy between the API specification in brightsky.yml and the actual result.

According to the yml, the `location` field should be an array, but it seems to be ever a single object.

I created a REST client in Microsoft Visual Studio from the yml file, and it returns an error when the request is executed.

I then adjusted the yml file as follows, and there was no more error and the result looks OK∴

From line 459:

```  
location
  type: array
    items:
      $ref: "#/components/schemas/Location"
```
replaced with:

```  
location:
    $ref: "#/components/schemas/Location"
```

**Comment by jdemaeyer** [comment]
Hi @miasbeck, thanks a lot for the report and for your research – you indeed hit the nail on the head! If you want you can create a pull request with the change you outlined so GitHub will show you as a contributor (as you deserve ;)), but if you feel that's too much trouble I can just add the change myself, just lemme know!

**Comment by miasbeck** [comment]
I would prefer you to make the changes yourself. I'm a layman when it comes to gitbub and pull requests and don't want to mess up this great repository. Thanks for reporting back!

**Comment by miasbeck** [comment]
The newly generated client works perfectly - happy to delete my "hack" now.

**Comment by jdemaeyer** [comment]
Perfect, thanks for checking!
