### ISSUE TITLE
Current weather data not updating

### ISSUE THREAD

**Issue by smilingchemist** [jdemaeyer/brightsky#164]
Hello, thank you (again) for this great api! Since 13:30 MESZ current weather data is not updating. Is there an issue?
Thank you, Frank

**Comment by jdemaeyer** [comment]
Ouch, thanks a lot for the report @smilingchemist! Our parsing worker crashed and I didn't pay close enough attention to my monitoring systems :/ Data should be back to normal in a couple of minutes.

**Comment by smilingchemist** [comment]
Perfect, thank you very much!

**Comment by jdemaeyer** [comment]
Follow-up: #165
