### ISSUE TITLE
Add Python/Docker packaging

### ISSUE THREAD

**Issue by Poeschl** [jdemaeyer/brightsky#82]
I just found your project and I thought adding it as a weather source for the Smart Home System [Home Assistant](https://www.home-assistant.io/). Since Dark Sky is shutting down end of the year, there are lots of people searching for new weather suppliers. Especially in Germany the quality of the available ones is not the best.

It would be nice to have your logic for polling and parsing of the DWD files in a python package to reuse it in a integration. Are there planes for that?

**Comment by jdemaeyer** [comment]
wow, an integration into Home Assistant would be awesome indeed!

Yes, I actually do plan to add proper packaging for PyPI and Dockerhub by the end of next week, seems I forgot to open an issue for it :)

**Comment by jdemaeyer** [comment]
Closed via 1e402e2c56fdcad03b8b02ced5b07e06dd811140

@Poeschl This is now available on PyPI as [`brightsky`](https://pypi.org/project/brightsky/) :)

#89 is a follow-up issue to avoid installing some deployment dependencies that are unnecessary if you only care about polling and parsing, but it's not high priority for me currently.

**Comment by Poeschl** [comment]
Nice 👍 When the current integration development is through, I will give it a shot.
