### ISSUE TITLE
Documentation inconsistency regarding sunshine

### ISSUE THREAD

**Issue by ialokim** [jdemaeyer/brightsky#96]
The `current_weather` and `synop` endpoints return in fact `sunshine_30` and `sunshine_60` instead of only `sunshine` as stated [in the documentation](https://brightsky.dev/docs/#get-/current_weather).

Btw, nice work!

**Comment by jdemaeyer** [comment]
Ooh la la, good catch, thanks!

**Comment by jdemaeyer** [comment]
Fixed via af8444e
